### ISSUE TITLE
Olx Fraud

### ISSUE THREAD

**Issue by pranshuchaurasia** [avinash201199/AvoidScams#4]
One of the main places where different types of scammers look for potential victims is classified advertisements. On such a forum, con artists can be found as both buyers and sellers. To conceal their genuine identity, they can go to a variety of lengths. They frequently pose as members of the Indian Army in order to dupe unsuspecting victims. Both of these fraudulent subtypes need to be on our radar.

**Comment by avinash201199** [comment]
thanks for this issue , please make a pr , will accept

**Comment by pranshuchaurasia** [comment]
PR created for the same. #5
